#!/bin/bash
set -xeu

# usage : bismark2bw input.bismak.cov output.bw
# ex. : ./bismark2bw data/example.sort.bismark.cov data/hg38.chrom.sizes data/out.bw 

# tmpファイルのID用に乱数を生成する。
ID=$RANDOM
echo $ID

# chrをchrom.sizesに含まれるものの未選択する。
cut -f1 $2 > tmp.${ID}.chr

grep -f tmp.${ID}.chr $1 | cut -f 1-4  > tmp.${ID}.bg
sort -k1,1 -k2,2n tmp.${ID}.bg > tmp.${ID}.sort.bg
bedGraphToBigWig tmp.${ID}.sort.bg $2 $3 

rm tmp.${ID}.chr
rm tmp.${ID}.bg
rm tmp.${ID}.sort.bg